#!/usr/bin/env bash

tmpbg=/tmp/pxllock.png

# if started by xsecurelock, set $tmpbg as its background
[[ ! -z "$XSCREENSAVER_WINDOW" ]] &&
    exec xloadimage -windowid "0x$(printf '%x' "$XSCREENSAVER_WINDOW")" "$tmpbg"

usage="pxllock <imagemaagick|maim|ffmpeg> <i3lock|xsecurelock> [locker arguments]"

# screenshot and pixelize
case "$1" in
    ffmpeg)
        ffmpeg -loglevel quiet -f x11grab -draw_mouse 0 -i "$DISPLAY" \
            -vf scale=iw/10:ih/10,scale=iw*10:ih*10:flags=neighbor \
            -frames:v 1 -y "$tmpbg"
        shift
        ;;
    imagemagick)
        import -window root "$tmpbg"
        convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
        shift
        ;;
    maim)
        maim -u -m 1 "$tmpbg"
        convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
        shift
        ;;
    *)
        echo "$usage"
        exit 1
        ;;
esac

is_paused="$(dunstctl is-paused)"

# chose locker
case "$1" in
    i3lock)
        [[ "$is_paused" = false ]] && dunstctl set-paused true
        "$@" --nofork -i "$tmpbg"
        [[ "$is_paused" = false ]] && dunstctl set-paused false
        ;;
    xsecurelock)
        [[ "$is_paused" = false ]] && dunstctl set-paused true
        XSECURELOCK_SAVER=$0 "$@"
        [[ "$is_paused" = false ]] && dunstctl set-paused false
        ;;
    *)
        echo "$usage"
        exit 1
        ;;
esac
